version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-image:
          filters:
            branches:
              only:
                - master
                - staging
                - dev
          context:
            - docker-hub-creds
      - deploy-docker:
          requires:
            - build-image
          context:
            - docker-hub-creds
      - deploy-heroku:
          requires:
            - deploy-docker
          context:
            - docker-hub-creds
            - heroku-creds

jobs:
  build-image:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build . -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG

  deploy-docker:
    machine: true
    steps:
      - run: |
          TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker pull $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-latest
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-latest

  deploy-heroku:
    machine: true
    steps:
      - run: |
          sudo apt-get update && sudo apt-get install aria2
          echo 'https://docs.google.com/uc?export=download&id='$ENV_TAR_FILEID | aria2c --input-file=-
          tar -xvf env.tar.xz && rm -rvf env.tar.xz
          bash ./create_dockerfile.sh
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          heroku container:login
          docker build . -t registry.heroku.com/$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH/worker
          docker push registry.heroku.com/$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH/worker