version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - master
                - staging
                - dev
      - deploy-docker:
          requires:
            - build-test
          context:
            - docker-hub-creds

jobs:
  build-test:
    machine: true
    steps:
      - checkout
      - run: docker build .

  deploy-docker:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build . -t ksssomesh12/py-aria-mirror-bot:$CIRCLE_BRANCH-$TAG
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push ksssomesh12/py-aria-mirror-bot:$CIRCLE_BRANCH-$TAG
          docker tag ksssomesh12/py-aria-mirror-bot:$CIRCLE_BRANCH-$TAG ksssomesh12/py-aria-mirror-bot:$CIRCLE_BRANCH-latest
          docker push ksssomesh12/py-aria-mirror-bot:$CIRCLE_BRANCH-latest
