version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-image:
          filters:
            branches:
              only:
                - master
                - staging
          context:
            - docker-hub-creds
      - deploy-docker:
          requires:
            - build-image
          context:
            - docker-hub-creds
      - deploy-heroku:
          requires:
            - deploy-docker
          context:
            -  heroku-creds

jobs:
  build-image:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build . -t ksssomesh12/tg-mirror-bot:$CIRCLE_BRANCH-$TAG
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push ksssomesh12/tg-mirror-bot:$CIRCLE_BRANCH-$TAG

  deploy-docker:
    machine: true
    steps:
      - run: |
          BUILD_NUMBER=`expr $CIRCLE_BUILD_NUM - 1` && TAG=0.1.$BUILD_NUMBER
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker pull ksssomesh12/tg-mirror-bot:$CIRCLE_BRANCH-$TAG
          docker tag ksssomesh12/tg-mirror-bot:$CIRCLE_BRANCH-$TAG ksssomesh12/tg-mirror-bot:$CIRCLE_BRANCH-latest
          docker push ksssomesh12/tg-mirror-bot:$CIRCLE_BRANCH-latest

  deploy-heroku:
    machine: true
    steps:
      - run: |
          sudo apt-get update && sudo apt-get aria2
          echo $BOT_ENV_LINK | aria2c --input-file=-
          tar -xvf env.tar.xz && rm -rvf env.tar.xz
          heroku container:login
          docker build . -t registry.heroku.com/$HEROKU_APP_NAME-$CIRCLE_BRANCH/worker
          docker push registry.heroku.com/$HEROKU_APP_NAME-$CIRCLE_BRANCH/worker